cmd/ejson/main.go, json/pipeline.go, json/walker.go
@Shopify/locutus 
Turns out encryption is pretty slow.
Time to decrypt test file fetched from  https://edg.epa.gov/data.json and encrypted with a random key:
On my macbook:
* Go 1.4, GOMAXPROCS=1, master branch: 7.8s
* Go 1.5, GOMAXPROCS=1, master branch: 5.8s
* Go 1.5, GOMAXPROCS=1, this branch: 6.9s
* Go 1.5, GOMAXPROCS=8, this branch: 1.9s
On production infrastructure (first is Go 1.4, 1 proc, master; second is Go 1.5, 32 procs, optimize branch):
```
burke@borg3.ash:~ $ ./test_deployed
7.371902681s
burke@borg3.ash:~ $ ./test_go_1.5_optimize_branch
794.795795ms
```
=> Parallelize encryption to improve performance

cmd/ejson/actions.go, ejson.go, ejson_test.go
- Updated `DecryptFile` to return a `[]byte` instead of a `string`.
- Now checks an error that was unchecked before.
- Updated the comments for `DecryptFile` to reflect what it's currently doing.
- Removed a test that looked like it was doing nothing.
cc @burke
=> Updated DecryptFile to return a byte slice

json/walker.go, json/walker_test.go
For review @burke @Roxot
ejson makes some irritating changes to whitespace. This PR is an attempt to preserve all whitespace from the input file. It's the first Go I've written, so I doubt I've done this in the most elegant way.
Fixes https://github.com/Shopify/ejson/issues/16
=> Preserve whitespace, including trailing newline.

cmd/ejson/actions.go
For review @burke @Roxot
This adds a trailing newline to key files, as suggested in #16.
I verified that the decrypt operation is happy with the new format.
Fixes #16.
=> Include newline in key file.

cmd/ejson/actions.go, cmd/ejson/main.go, ejson.go, ejson_test.go, man/man1/ejson-decrypt.1.ronn
Removes the need to write the private key to decrypt an EJSON file.
Background: https://github.com/Shopify/ejson/pull/41
```
❯ ejson --private-key [private_key] decrypt test.ejson
{
"_public_key": "[public_key]",
"test": "sssh!"
}
```
=> Flag to read private key from STDIN

Gemfile.lock, cmd/ejson/actions.go, cmd/ejson/main.go, dev.yml
It'd be nice if commands like `ejson d` only ever output a json blob, and put their error messages into stderr
Also upgraded bundler, and changed dev test to test everything, not just the root dir
=> Print error messages to stderr

cmd/ejson2env/ejson2env.1.ronn, cmd/ejson2env/env.go, cmd/ejson2env/env_test.go, cmd/ejson2env/key.go, cmd/ejson2env/main.go, cmd/ejson2env/secrets.go, cmd/ejson2env/test.ejson, cmd/ejson2env/version.go
This pull request adds the ejson2env command, which aids with the export of environment variables stored in ejson files.
For example, with an ejson file containing:
```
{
"_public_key": "<key>",
"environment": {
"DB_PASSWORD": "EJ[1:OrYT5AaCMOtskq44s2rIzZnoeWW9y5ciYEiV8FWAORc=:vlYfnSz0wuGHKXZ1yFqVnFP5PYrTNyMs:UR5ZeX7BnDWeoAjiy1Rp/nTDWsmmYtJrWmI=]"                                                                                                                               
}
}
```
Running `ejson2env` would output:
```
export DB_PASSWORD=test1234
```
This command would then be called in entrypoint shell scripts.
=> adds ejson2env

cmd/ejson/actions.go
Closes #55 
Closes #58
I agree that both of these cases should be stdout rather than stderr: neither are error cases, nor must either be separated from a stdout stream that's useful to redirect elsewhere.
=> Move non-error output back to stdout

cmd/ejson/main.go, go.mod, go.sum
When fetching ejson via `go get github.com/Shopify/ejson/cmd/ejson` we received the following error:
```
[2019-05-28T18:52:07Z] # github.com/Shopify/ejson/cmd/ejson
[2019-05-28T18:52:07Z] src/github.com/Shopify/ejson/cmd/ejson/main.go:26:18: \
cannot use func literal (type func(string, interface {})) as type cli.helpPrinter in assignment
```
* Bump the version of `cli` to the latest tag
* Fix up the custom help command to match the func type
* Update references for `codegangsta/cli` to `urfave/cli` since this is where the lib lives now.
=> Issues with cli.helpPrinter signature when go getting

CONTRIBUTING.md, README.md
I realize now it makes more sense to have build instructions in CONTRIBUTING.md rather than README.md.
=> Move FreeBSD build instructions to CONTRIBUTING.md

dev.yml
Running `make all` would fail with a fpm error:
```
bundle exec fpm \
-t deb \
-s dir \
--name="ejson" \
--version="1.2.1" \
--package="pkg/ejson_1.2.1_amd64.deb" \
--license=MIT \
--category=admin \
--no-depends \
--no-auto-depends \
--architecture=amd64 \
--maintainer="Shopify <admins@shopify.com>" \
--description="utility for managing a collection of secrets in source control. Secrets are encrypted using public key, elliptic curve cryptography." \
--url="https://github.com/Shopify/ejson" \
./build/man/=/usr/share/man/ \
./build/bin/linux-amd64=/usr/bin/ejson
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag …
```
=> Add `gnu-tar` as a dev dependency 

README.md
There is an incorrect command in the README under Step 2 of Workflow to generate a keypair.
`./ejson keygen -w` will give error `no such file or directory: ./ejson`
It should run the `ejson keygen` command with the write flag `-w`
=> Fix README command to generate keypair with write flag

Gemfile.lock, dev.yml
Trying to install it on MacOS Big Sur shows the following problem:
```
┃┃ Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
┃┃     current directory: /Users/plentz/.gem/ruby/2.7.2/gems/rdiscount-2.2.0.1/ext
┃┃ /opt/rubies/2.7.2/bin/ruby -I /opt/rubies/2.7.2/lib/ruby/2.7.0 -r ./siteconf20210117-58583-mrp5in.rb extconf.rb
```
[rdiscount `2.2.0.2` fixed the compilation error.](https://github.com/davidfstr/rdiscount/blob/master/CHANGELOG.md) 
<details>
<summary>Click to expand</summary>
```
➜  ejson git:(master) ✗ dev up
⭑ Global System Setup
┏━━ 👩‍💻  1/5 Homebrew setup ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ …
```
=> Update dependencies (ruby and rdiscount)

.github/workflows/release.yml
Build and upload release artifacts from GitHub Actions, using the existing goreleaser configuration.
Having an automated release process transfers the trust from the uploading developer to GitHub's infrastructure. It is a requirements for [SLSA level 1](https://slsa.dev/spec/v0.1/levels).
- Closes https://github.com/Shopify/ejson/issues/92
- Related https://github.com/Shopify/ejson/issues/68 (via https://goreleaser.com/customization/sign/ )
=> actions: release workflow

dev.yml, ejson.go, ejson_test.go, json/walker.go, json/walker_test.go, man/man5/ejson.5.ronn
A common use-case is to want to paste in multiline certificates, etc.
This does a first pass on encrypt in order to first collapse multiline strings into valid JSON, before continuing with handling.
=> Collapse newlines in string literals:

.github/workflows/release.yml
- https://github.com/Shopify/ejson/issues/129
goreleaser was old (v1.2.1) so it failed to release an asset for darwin/arm64
https://github.com/Shopify/ejson/actions/runs/4872615287/jobs/8691044230#step:6:30
```
• DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.
```
To fix the issue, I update goreleaser to the latest version v1.18.1. Then I've confirmed the issue has been solved.
```console
$ goreleaser --version
____       ____      _
/ ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
\____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible …
```
=> ci: update goreleaser to v1.18.1 to release assets for darwin/arm64

.github/dependabot.yml
I did bundler too - https://github.com/Shopify/ejson/commit/2d2a849ccafff153829c6dfd3438215b2bae2172
That was how I realized there was no branch protection 🤦
=> dependabot: github-actions

.goreleaser.yaml, Makefile, cmd/ejson/actions.go, cmd/ejson/version.go
Replace the logic in `Makefile` that replaces `cmd/ejson/version.go` with the current tag.
It's more common to inject these variables during linking, instead of generating source code.
Verify like:
```
$ cat cmd/ejson/version.go
package main
var VERSION string = "1.5.0"
$ goreleaser build --snapshot --rm-dist
$ dist/ejson_darwin_arm64/ejson --version
ejson version 1.5.1-SNAPSHOT-1ecf7d7
```
=> goreleaser: embed VERSION

.github/workflows/release.yml
In #154 we started uploading `.deb` artifacts.
I forgot we only sign `*.tar.gz`, so the deb's lack provenance. I can not abide.
=> release: sign .deb

Makefile
Looks like a typo in the `Makefile`. 
Though after making this change I realise it wasn't actually breaking anything.  The `$(ARM64_DEB)` rule target is redundant because all roads lead to `goreleaser release`, which handles the packaging for all systems and architectures.
=> Fixed a typo in Makefile where ARM64_DEB wasn't defined
